# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHUeLgNT5PnhBZRmjmzvv4SS8P6ZkcZ-
"""

n = int(input("Enter a number: "))
i = 1
while i <= n:
    print(i)
    i += 1

alphabets = 'a'
while alphabets <= 'z':
    print(alphabets)
    alphabets = chr(ord(alphabets) + 1)

i = 1
while i <= 100:
  if i%2==0:
    print(i)
  i+=1

sum = 0
n = int(input("Enter a number:"))
while(n!=0):
  if(n%2!=0):
    sum+=n
  n-=1
print(sum)

num = int(input("Enter a number: "))
count = 0
while num != 0:
    num //= 10
    count += 1
print("Number of digits:", count)

num = int(input("Enter a number: "))
sum = 0
while num != 0:
    sum += num % 10
    num //= 10
print("Sum of digits:", sum)

n = int(input("Enter a number: "))
first = 1
last = 0
while n != 0:
    last = n % 10
    n //= 10
print("First digit:", first)
print("Last digit:", last)

n = int(input("Enter a number: "))
rev = 0
while n != 0:
    rev = rev * 10 + n % 10
    n //= 10
print("Reversed number:", rev)

i = 1
power = 1
n = int(input("Enter a number: "))
p = int(input("Enter the power: "))
while i <= p:
    power *= n
    i += 1
print("Result:", power)

factorial = 1
n = int(input("Enter a number: "))
for i in range(1, n + 1):
    factorial *= i
print("Factorial:", factorial)

num=int(input("enter a number: "))
a=0
for i in range(2,num):
  if num%i==0:
    a=1
    break 
if a==1:
  print("not prime")
else:
  print("prime",num)
    n = int(input("Enter a number: "))
i = 1
while i <= n:
    print(i)
    i += 1

alphabets = 'a'
while alphabets <= 'z':
    print(alphabets)
    alphabets = chr(ord(alphabets) + 1) -1
    
